### ISSUE TITLE
npm is on the machine but "npm not found" Linux

### ISSUE THREAD

**Issue by diestrin** [720kb/ndm#81]
* OS: OSx
* OS version: 10.11.6
* Ndm version: 0.0.3-beta
* Node version: Multiple
* Npm version: Multiple
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): doesn't matter
* Node installed via (brew, n, nvm, pkg, other ...): nvm
* How to replicate the bug/issue, if you know:

When I open the app it says there's no npm in my machine
![Missing npm](https://api.monosnap.com/rpc/file/download?id=emlkV4AefCoqomMNldZzbK5KMajVpx)

**Comment by 45kb** [comment]
Hi @diestrin  weird what this `npm -v` prints in your terminal?

**Comment by diestrin** [comment]
I dependes on what version of node I want to use...
For node 6.9.1 I have npm 3.10.8

**Comment by 45kb** [comment]
It's very important to check what's happening, could you please try this:

- clone https://github.com/720kb/ndm
- put some console.log() here https://github.com/720kb/ndm/blob/master/lib/js/npm/npm-api.js#L87
- npm i && npm start
- once the app is shown click (from the OS Menu -> Electron -> Debug) , you'll get the console inside the app, then check what is printed in console.

Thanks

**Comment by 45kb** [comment]
@diestrin perhaps... do you uninstalled or installed npm globally using ndm?

**Comment by RSDessin** [comment]
I have a similar problem.
I open the app it says there's no npm in my machine too.

OS: Mac OS
OS version: 10.12.2
Ndm version: 0.1.2
```
$ node -v
v6.9.3
$ npm -v
3.10.10
$ which npm
/usr/local/bin/npm
```

**Comment by 45kb** [comment]
@RSDessin i wasn't sure how to replicate the problem, then it happened to me weirdly so it's definitely an issue, thanks for reporting!

**Comment by 45kb** [comment]
@diestrin @RSDessin seems fixed 👍  you can try the new version (v0.1.3) download link: https://720kb.github.io/ndm/#linux

If any problem let know, thanks!

**Comment by RSDessin** [comment]
@45kb 
thank you your response.
I tried v0.1.3

The problem continues.
What kind of information should I provide?


> You have not installed npm on your machine.
> 
> Error: Command failed: npm -v
> /bin/sh: npm: command not found

===
```
sh-3.2$ npm -v
4.0.5
sh-3.2$ node -v
v6.9.4
sh-3.2$ which npm
/usr/local/bin/npm
```
```
bash-3.2$ npm -v
4.0.5
bash-3.2$ node -v
v6.9.4
bash-3.2$ which npm
/usr/local/bin/npm
```

**Comment by 45kb** [comment]
@RSDessin  so we need to investigate better this, i had the same problem but it's fixed now on my side.

How you installed node?

When you open the app you see the alert, if you "Restart" the app by Ctrl+R you still see the alert?

If you dismiss the alert ... then are you able to install or update global packages?

**Comment by RSDessin** [comment]
@45kb 
I installed it in the following way.
https://nodejs.org/en/download/

Alerts are still displayed.
![image](https://cloud.githubusercontent.com/assets/3080432/21976532/a88a63d0-dc15-11e6-99fc-4ff498119af5.png)

I clicked "update npm", but the update will not start.
![image](https://cloud.githubusercontent.com/assets/3080432/21976488/73bb9f98-dc15-11e6-97ae-af6b1370f89c.png)

> If you open different terminal windows, are you able to install global packages without permissions in each new window?

yes.
```
bash-3.2$ npm install -g grunt-cli
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/lib
└─┬ grunt-cli@1.2.0 
  ├─┬ findup-sync@0.3.0 
  │ └─┬ glob@5.0.15 
  │   ├─┬ inflight@1.0.6 
  │   │ └── wrappy@1.0.2 
  │   ├── inherits@2.0.3 
  │   ├─┬ minimatch@3.0.3 
  │   │ └─┬ brace-expansion@1.1.6 
  │   │   ├── balanced-match@0.4.2 
  │   │   └── concat-map@0.0.1 
  │   ├── once@1.4.0 
  │   └── path-is-absolute@1.0.1 
  ├── grunt-known-options@1.1.0 
  ├─┬ nopt@3.0.6 
  │ └── abbrev@1.0.9 
  └── resolve@1.1.7 
```

**Comment by 45kb** [comment]
@RSDessin thanks we'll try to investigate this better, maybe some timing problems unfortunately.

Does it works if you restart the app without closing it ?

**Comment by RSDessin** [comment]
@45kb 

No, it does not work.
![image](https://cloud.githubusercontent.com/assets/3080432/21977442/7b791194-dc19-11e6-9f37-34eb711fae17.png)

**Comment by 45kb** [comment]
@RSDessin thanks once more, we'll try to see what's happening, i am sorry for this.
However ( if you can and want) try install npm from nvm or brew ... at least  (in the meantime) you should be able to use the app, otherwise doesn't matter really 👍 , we'll investigate this.

**Comment by 45kb** [comment]
@RSDessin one last thing if you can, go to the devtools console and write in console `process.env.PATH` then paste the output here, thanks!

**Comment by RSDessin** [comment]
@45kb 

![image](https://cloud.githubusercontent.com/assets/3080432/22003654/87e19166-dc98-11e6-93ca-af26c34c7a8f.png)

**Comment by 45kb** [comment]
@RSDessin odd, this is the problem i am quite sure. thanks i'll let you know.

**Comment by RSDessin** [comment]
![image](https://cloud.githubusercontent.com/assets/3080432/22056480/a5372152-dda3-11e6-923b-1df03de7e4bb.png)

Thank you for your help.

My PC did not solve it.
Since I successfully installed it as I tried on another new PC,
I think that it is a problem unique to my PC.

**Comment by 45kb** [comment]
@RSDessin you're welcome, i think this errors comes when there are some troubles with npm permissions or node is not installed the correct way, it's weird and what i suggest you is to use a tool (homebrew or nvm or n) to handle node and npm installation so that you can be quite sure that is installed correctly. 

We are fixing many problems in the meantime and the next release aims to be really more stable.

I'll update you as we release a new version so you can try it.

If you want you can do one thing more, clone the repo, run `npm install` and `npm run mac` so you can try the very latest (in development) version of the app and see if it fixs your problems 👍

**Comment by 45kb** [comment]
@RSDessin try the new version if you want https://github.com/720kb/ndm/releases/tag/v0.1.4
Seems really more stable and many bugs are fixed.

**Comment by 45kb** [comment]
@RSDessin if you can try the new v0.1.4 released now https://github.com/720kb/ndm/releases/tag/v0.1.4

It has a lot of bugs fixed inside, let me know then if it was a problem restricted to your PC only, because i never faced this error anymore and it seems fixed for us, seriously not able to reproduce it anyhow (which sounds great but let me know)

Thanks for your patience.

**Comment by RSDessin** [comment]
Thank you for your help.

I tried a new version, but it did not solve it.
It seems to be just my PC problem.

I appreciate your help.

**Comment by 45kb** [comment]
@RSDessin thank you too, i will close the issue and possibly re-open it as soon as this behavior repeats on some other's PC 👍
